admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /

#core:
#    resource: "@CoreBundle/Resources/config/routing.yml"
#    prefix:   /