<?php

namespace CoreBundle\Repository;

/**
 * PostPrintMaterial
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostPrintMaterialRepository extends \Doctrine\ORM\EntityRepository
{
}
