<?php

namespace CoreBundle\Repository;

/**
 * PostPrintOperationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostPrintOperationRepository extends \Doctrine\ORM\EntityRepository
{
}
