<?php

namespace CoreBundle\Repository;

/**
 * PrintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrintingRepository extends \Doctrine\ORM\EntityRepository
{
}
